### ISSUE TITLE
Installation fails for Jazzy

### ISSUE THREAD

**Issue by orfvl** [moveit/moveit2#2833] opened 2024-05-16 06:38 UTC
### Description

Overview of your issue here.

### Your environment
* ROS Distro: Jazzy
* OS Version:  Ubuntu 24.04
* Source or Binary build? Source
* If binary, which release version?
* If source, which branch? Master
* Which RMW (Fast DDS or Cyclone DDS)? Humble or Rolling should be using Cyclone. Dont know

### Steps to reproduce
I followed the instructions to install ros2 [jazzy](https://docs.ros.org/en/jazzy/Installation/Ubuntu-Install-Debians.html). 
Then I followed with instructions for [moveit](https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html). Until building the workspace everything was fine.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
When i executed
```
sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
```
I get the following error 
```
executing command [sudo -H apt-get install -y ros-jazzy-gazebo-ros2-control]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ros-jazzy-gazebo-ros2-control
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-jazzy-gazebo-ros2-control] failed
  apt: Failed to detect successful installation of [ros-jazzy-gazebo-ros2-control]
```

Any help would be greatly appreciated.

### Edit
I noticed when running 
```
sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
```
That it tries to find `gazebo_ros2_control` which is Gazebo classic meaning "Gazebo Classic is not released to Ubuntu Noble. As a consequence, gazebo_ros2_control won’t be released for Jazzy and Rolling anymore."

Is it possible to change this in the moveit installation?

**Comment by henningkayser** [comment] 2024-05-24 15:00
Jazzy is not yet supported by MoveIt, release and support progress is tracked here #2846.

Your issue is indeed caused by gazebo_ros2_control not being available as debian package anymore, and gz_ros2_control being the successor to switch to.

Also, this dependency is not a MoveIt dependency, more likely it is being installed by one of the tutorial resources. If you could track down which one that is and update the dependency, that would be very helpful for the migration. I'm closing this issue for now since it doesn't affect any of the supported distros.

**Closed by henningkayser** 2024-05-24 15:00 UTC
Labels: bug
