### ISSUE TITLE
Support both Node and LifecycleNode

### ISSUE THREAD

**Issue by tylerjw** [moveit/moveit2#1737] opened 2022-11-18 03:31 UTC
Here is a possible implementation of adapting moveit to support both the Node and LivecycleNode:

- https://github.com/ros-planning/moveit2/pull/1329

If users are going to use moveit and hand MoveIt a node object we should consider supporting both the Node and LifecycleNode.

**Comment by mikeferguson** [comment] 2024-12-17 16:13
Duplicate of #1538

**Closed by mikeferguson** 2024-12-17 16:13 UTC
Labels: enhancement, persistent
