### ISSUE TITLE
Fix overriding binary install

### ISSUE THREAD

**Issue by tylerjw** [moveit/moveit2#1928] opened 2023-02-03 20:04 UTC
Overriding is when you build a package from a source that is also installed as a binary. Currently, this does not work in MoveIt because of the way header files are found. The problem is that the binary header is found before the source header when building and if the source one is newer and has changes the compile will break in surprising ways.

#1901 is a good example of what needs to be done everywhere in moveit. 

Here are the colcon docs on overriding: https://colcon.readthedocs.io/en/released/user/overriding-packages.html#how-to-make-it-easier-for-your-users-to-override

Tasks:
- [ ] Search for cmake files that are missing this package directory
- [ ] Make PR fixing the issue

**Comment by bailaC** [comment] 2023-05-30 13:50
@tylerjw I think we can close this issue as it is already merged.

**Comment by sjahr** [comment] 2023-12-11 07:59
@mariobo8 Yes, go for it.

**Comment by advait-zx** [comment] 2024-09-21 19:31
is this issue still open?

**Comment by mikeferguson** [comment] 2024-12-17 16:06
Duplicate of https://github.com/moveit/moveit2/issues/3134 which has more recent documentation to work from

**Closed by mikeferguson** 2024-12-17 16:06 UTC
Labels: good first issue
